### ISSUE TITLE
where to find the web access code to Tesla Management Portal?

### ISSUE THREAD

**Issue by vincentmli** [wardmundy/php-api-tesla#1]
Hi, 

in the config.php
// specify the code for web access to Tesla Management Portal
$web_access=123456;

where/how I can find the web access code ? is the web access code  unique to everyone?

**Comment by wardmundy** [comment]
It's a unique number that you make up. It will be used to access the web
portal once it becomes available.

Ward Mundy & Associates LLC

Follow Us
<https://www.facebook.com/WardMundy>
<https://plus.google.com/u/0/+WardMundy/posts> <https://twitter.com/NerdUno>
<http://youtube.com/wardmundy/>

**Comment by wardmundy** [comment]
It's a unique number that you make up. It will be used to access the web portal once it becomes available.
